# This file is a template, and might need editing before it works on your project.
image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    # Default cache directory from https://classic.yarnpkg.com/en/docs/install-ci/#gitlab.
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/

before_script:
  - cd lib/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - lib
  only:
    - master
test:
  stage: test
  script:
    - npm install
    - npm run test
  only:
    - master
deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
    - npm run storybook:build
    - cd ../pages
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
