# This file is a template, and might need editing before it works on your project.
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - lib/node_modules/
    - node_modules/

before_script:
  - cd lib/

stages:
  - build code
  # - pages

build-stage:
  stage: build code
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master

# pages:
#   script:
#     # - npm install
#     - ./node_modules/.bin/gatsby build --prefix-paths
#   artifacts:
#     paths:
#       - public
#   only:
#     - master
