# This file is a template, and might need editing before it works on your project.
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - lib/node_modules/
    - node_modules/

before_script:
  - cd lib/

stages:
  - build code
  - deploy

build-stage:
  stage: build code
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master

pages:
  stage: deploy
  script:
    - npm install
    - npm run storybook:build
  artifacts:
    paths:
      - public
