# This file is a template, and might need editing before it works on your project.
image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    # Default cache directory from https://classic.yarnpkg.com/en/docs/install-ci/#gitlab.
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/

before_script:
  - cd lib/

stages:
  - build
  - test
  - pages

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - lib

test:
  stage: test
  script:
    - npm install
    - npm run test

pages:
  stage: pages
  script:
    - npm install
    - npm run build
    - npm run storybook:build -o ../public/storybook # will resolve to ./public/storybook because we're in /lib
    - cd ../pages
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
    - cd ..
    - rm -rf public # this will overwrite the current storybook output
    - mv pages/public .
  artifacts:
    paths:
      - public
  only:
    - master
